version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USERNAME=DB_USERNAME
      - DB_PASSWORD=DB_PASSWORD
      - DB_HOSTNAME=db
      - DB_PORT=DB_PORT
      - DB_NAME=DB_NAME
    ports:
      - "5005:5005"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
